class_name SetDressing extends Control
#loader karakterene som scener
const CHARA1 = preload("res://character_example.tscn")
const CHARA2 = preload("res://character_example2.tscn")
const CHARA3 = preload("res://character_example_3.tscn")
const CHARA4 = preload("res://character_example_3.tscn")
const CHARA5 = preload("res://character_example_3.tscn")

func _ready() -> void:
	#instantiater karakterene
	var o:VNCharacter=CHARA1.instantiate()
	var r:VNCharacter=CHARA2.instantiate()
	var q:VNCharacter=CHARA3.instantiate()
	var h:VNCharacter=CHARA4.instantiate()
	var k:VNCharacter=CHARA5.instantiate()
	#tilføjer dem til scenen
	add_child(o)
	add_child(r)
	add_child(q)
	add_child(h)
	add_child(k)
	#kommandoer som kan udføres:
	#_.snap(%position)
	#_.move(%position,tid brugt på bevægelse)
	#_.say("navn", "Hvad der skal siges") (brug \n til at gå en linje ned og tilføj 2 mellemrum)
	#_.flip_(h/v)=(true/false)
	#_.attr("navn på alternativ udseende på karakter")
	#await venter på den sidste kommando er færdig til at udføre den næste
	o.snap(%far_left)
	r.snap(%far_left)
	q.snap(%far_left)
	h.snap(%far_left)
	k.snap(%far_left)
	%background.texture=load("res://backgrounds/Classroom.png")
	var transition1=create_tween()
	transition1.tween_property(%background, "modulate:a", 0, 0)
	transition1.tween_property(%background, "modulate:a", 1, 2)
	await o.move(%far_left,2.5)
	await o.say("You","It’s only been a few weeks since I’ve started high school.\n  So far high school life has been as dull as I expected. \n  It’s nothing like how it is in manga.")
	print("sentance 1 complete, signal emit")
	await o.say("You","I still have to join a club soon,\n  I’ve been waiting it out for a good while now.\n  It’s practically been pushed to the back of my mind.")
	print("sentance 2 complete, signal emit")
	await o.say("You","I could continue to wait till the festival, \n  all the different clubs should be at their \n  best marketing-wise then.")
	print("sentance 3 complete, signal emit")
	await o.say("YOU","But, it would be embarrassing to be walking around\n  as one of those clubless. Especially if everyone else \n  has already found a club.")
	print("sentance 4 complete, signal emit")
	await o.say("YOU","Yeah, that’s definitely not happening.")
	await o.say("YOU","But what kind of club should I even join? \n  Perhaps something that doesn’t require much. \n  Like some kind of manga or anime club.")
	await o.say("YOU","If we even have clubs like that…")
	await o.say("YOU","Guess I really have to go around looking after school.")
	await o.say("YOU","After class finishes, I continue to sit at\n  my desk and wait a bit longer. \n  Building up the courage to go club hunting")
	await o.say("YOU","I would rather not have my classmates think\n  I’m some loser. After all, I only go home and do nothing\n  but play video games.")
	await o.say("YOU","Not long after dismissal, everyone funneled out the\n  classroom, heading to their own after school activities.")
	await o.say("YOU","I wait for the coast to be clear before I make my move.")
	await o.say("YOU","I gather my belongings and leave like everyone else.\n  Except this time, I’m not going home.")
	var transition2=create_tween()
	transition2.tween_property(%background, "modulate:a", 0, 1.5)
	await o.move(%far_left,2)
	%background.texture=load("res://backgrounds/HallwayLeftToRight.png")
	var transition3=create_tween()
	transition3.tween_property(%background, "modulate:a", 0, 0)
	transition3.tween_property(%background, "modulate:a", 1, 1.5)
	await o.move(%far_left,2)
	await o.say("YOU","I walk down the hallway. I can’t help but feel out of place,\n  even though I’ve been here multiple times every day. \n  It feels like I took a wrong turn on a familiar road.")
	await o.say("YOU","I’ve already passed a few clubs by now, \n  but none of them stood out to me.")
	await o.say("YOU","Luckily no one's seen me out here yet. \n  The worst thing that could happen right now is-")
	await o.move(%leftishUpleftUp,0.5)
	await o.move(%leftish,0.5)
	await o.say("Sentry","\"CRAP I’M GONNA BE LATE!!!\"")
	await o.say("YOU","Then, like clockwork I run into an old friend, \n  the one thing I was trying to avoid.")
	await o.say("YOU","He’s running through the halls like a complete lunatic, \n  almost running straight into me.")
	await o.move(%leftishDownLeft,0.5)
	await o.say("YOU","He barely misses me, I’d have hoped he kept going. \n  But he stops dead in his tracks and turns to me, \n  definitely recognizing me.")
	await o.move(%centerUp, 0.75)
	o.flip_h=true
	await o.say("Sentry","\"YOU!\"")
	await o.say("Sentry","\"Uh It's you!\"")
	await o.say("Sentry","\"From last year.\"")
	await o.say("Sentry","\"No not last year-\"")
	await o.say("YOU","Last year I would still have been in middle school. \n  It’s been a while since then, we didn’t know each other exactly.")
	await o.say("YOU","He’s a year older than me but was still a friend of a friend, so I’ve seen him a few times.")
	await o.say("Sentry","\"Wait we’re actually in the same school, what a coincidence!\"")
	await o.say("YOU","\"“Well yeah…It’s the closest one in the area.”\"")
	await o.say("Sentry","\"More like the only one in the area!\"")
	await o.say("Sentry","\"Ugh I could be nice to not have to take the train for once.\"")
	await o.say("YOU","\"Walking distance would definitely be cheaper…\"")
	await o.say("Sentry","\"Oh crap, my club! KING is going to kill me!\"")
	await o.say("YOU","He certainly hasn’t changed. He’s still as energetic and forgetful as ever. He’s nearly impossible to escape from when trapped in a conversation with him.")
	await o.say("YOU","\"\"“Well, you should probably hurry then.”")
	await o.say("Sentry","\"Don’t you have a club you should be getting to as well?\"")
	await o.say("Sentry","\"We can walk there together!\"")
	await o.say("Sentry","\"Unless you’re in the science club of course.\"")
	await o.say("YOU","\"Oh yeah…\"")
	await o.say("YOU","He’s right, there’s nothing but the science club that way. I don’t have much of a way out of this…")
	await o.say("YOU","\"Well...I- \"")
	await o.say("Sentry","\"You’re not in a club?!\"")
	await o.say("YOU","\"How did you-?\"")
	await o.say("Sentry","\"Oh it was just a guess ha-ha\"")
	await o.say("Sentry","\"You should totally join mine!\"")
	await o.say("YOU","\"I was already looking around so- \"")
	await o.say("Sentry","\"Then come look at ours it’s not that far of a walk, come it’s just this way!\"")
	await o.say("YOU","I can barely get a word in. He’s already decided to get me to join his club, there’s no way I’m getting out of this. Once he sets his sights on something, he never gives up till it’s done.")
	await o.say("Sentry","\"Oh I know you’re going to love it, it’s all about games, games and more games!\"")
	await o.say("Sentry","\"You still play video games, right?\"")
	await o.say("YOU","\"Yeah.\"")
	await o.say("YOU","Sentry is practically dragging me down the hallway, it seems like I have no choice but to go.")
	await o.say("YOU","He’s still blabbering on, switching from subject to subject. I haven’t even said a word the entire time.")
	await o.say("YOU","As soon as we get to the club room, Sentry enthusiastically slides the door open. Creating a loud thud that echoes throughout the room as well as the hallway.")
	await o.say("Sentry","\"Everyone! I’ve got us a new member!!!\"")
	await o.say("YOU","He yells out into the room, immediately getting everyone’s attention.")
	await r.say("Ravager","\"What is this about Sen.\"")
	await q.say("Quickshot", "\"You’ve gotten a member? Is that where you have been?\"")
	await r.say("Ravager","\"See, I told ya he didn’t kick the bucket.\"")
	await h.say("Harbinger","\"...\"")
	await h.say("Harbinger","\"You lost, again.\"")
	await r.say("Ravager","\"Huh!? That’s not fair!\"")
	await r.say("Ravager","\"They were distracting me!\"")
	await r.say("Ravager","\"Ay run it back! I’m not conceding to you!\"")
	await h.say("Harbinger","\"Whatever...\"")
	await o.say("YOU","\"Uhm\"")
	await o.say("Sentry","\"Hah don’t mind them, they can get a tad bit to competitive…\"")
	await o.say("YOU","The air certainly gets tense around them, I would rather avoid being near both at the same time.")
	await q.say("Quickshot", "\"You two, perhaps there’s something more important than your game.\"")
	await q.say("Quickshot", "\"A certain new member…\"")
	await h.say("Harbinger","\"Tch\"")
	await r.say("Ravager","\"Hey, you got skills?\"")
	await o.say("YOU","\"Uh me?\"")
	await r.say("Ravager","\"Does it look like I’m asking anyone else!?\"")
	await o.say("Sentry","\"Come on don’t be like that.\"")
	await o.say("Sentry","\"You don’t want to make another terrible first impression- \"")
	await o.say("YOU","Sentry rests his arm on Ravs shoulder. However, Rav just shrugs his shoulders, seemingly ignoring him.")
	await q.say("Quickshot", "\"Would I be correct in assuming that you have yet to introduce us?\"")
	await o.say("Sentry","\"Ah introductions!\"")
	await o.say("Sentry","\"Agh it completely slipped my mind!\"")
	await r.say("Ravager","\"Hah dummy.\"")
	await k.say("KING","\"How about you introduce us then Sentry?\"")
	await o.say("YOU","A figure approaches with such confidence, I can only assume that this must be the club leader. After all he’s precise and straightforward.")
	await q.say("Quickshot", "\"Oh your back, did they have Harbinger’s charger in lost and found?\"")
	await k.say("KING","\"Yep, I just put it on the desk over there.\"")
	await k.say("KING","\"So in my absence you’ve managed to reel in a new member?\"")
	await o.say("Sentry","\"KING! I’m so sorry for being late! It won’t happen again I swear!\"")
	await r.say("Ravager","\"You idiot! You don’t mention it when the boss isn’t here!\"")
	await o.say("Sentry","\"Ah sorry!\"")
	await o.say("YOU","He’s who Sentry mentioned before, there’s no way he’s not the club leader.")
	await k.say("KING","\"There’s no need for apologies, after all you bring with you a new member.\"")
	await o.say("Sentry","\"phew I’m off the hook.\"")
	await k.say("KING","\"I’m guessing the two of you are already acquainted?\"")
	await o.say("YOU","\"Yeah, we went to the same middle school.\"")
	await o.say("YOU","Rav leans towards Sentry clearly trying to whisper something.")
	await r.say("Ravager","\"There’s no way he’s also from our middle school.\"")
	await o.say("YOU","However, he clearly isn’t used to keeping his voice down. I wouldn’t be surprised if everyone heard him.")
	await o.say("Sentry","\"Player! Ravager also went to our middle school, isn’t that cool!\"")
	await r.say("Ravager","\"Does that really matter...\"")
	await r.say("Ravager","\"It’s not like we’ve ever met.\"")
	await o.say("YOU","I most definitely don’t remember meeting anyone like him. I don’t even think I remember seeing anyone like him with Sentry back then.")
	await o.say("YOU","Although it’s not like He didn’t surround himself with all kinds of people, it’s totally possible.")
	await o.say("Sentry","\"I think I would remember if that were the case.\"")
	await r.say("Ravager","\"I doubt it.\"")
	await r.say("Ravager","\"I used to run with a different crowd back then.\"")
	await r.say("Ravager","\"Not like that matters, there’s more interesting people than me here.\"")
	await o.say("Sentry","\"Right! Like our very own totally influential student council member!\"")
	await q.say("Quickshot", "\"Previous council member.\"")
	await o.say("YOU","Very clearly deflecting, he doesn’t seem to be used to receiving praise.")
	await q.say("Quickshot", "\"Not that I understand why you always mention that to people...\"")
	await q.say("Quickshot", "\"It’s only from when I was a first year, it’s not that impressive.\"")
	await k.say("KING","\"You say that as if you weren’t the one responsible for us getting actual good snacks in the vending machine.\"")
	await h.say("Harbinger","\"We haven’t heard this one before.\"")
	await o.say("Sentry","\"Wait you did what!? As a first year!?\"")
	await o.say("YOU","He’s certainly one of their more experienced members, totally a third year.")
	await q.say("Quickshot", "\"Didn’t we talk about not sharing too much about our first year?\"")
	await k.say("KING","\"Sorry, it slipped out.\"")
	await k.say("KING","\"I couldn't help but share my admiration of my vice president⁓\"")
	await o.say("Sentry","\"So you guys are the 3rd years.\"")
	await k.say("KING","\"Yup, were the reason why this club hasn't burnt to the ground.\"")
	await k.say("KING","\"You lot certainly don't make it easy for us...\"")
	await k.say("KING","\"We are graduating soon y'know.\"")
	await o.say("Sentry","\"You don't have to worry boss!\"")
	await r.say("Ravager","\"Yeah, Sentry has already gotten us some fresh meat.\"")
	await r.say("Ravager","\"So we already meet the five club members requirement for next year.\"")
	await o.say("YOU","\"Wait I-\"")
	await o.say("YOU","Suddenly everyone's turned their attention towards me. Even though I've never actually agreed to join the club, they have all written me off as a new member.")
	await k.say("KING","\"Is that so?\"")
	await k.say("KING","\"Has this person actually agreed to join or are you spouting nonsense again, Sentry?\"")
	await o.say("YOU","Sentry seems to try and get words out, but instead just bites his tongue and stays silent.")
	await o.say("YOU","Is the authority of the club leader overwhelming enough to silence even Sentry. The mood has definitely soured now.")
	await o.say("YOU","It's true that I never agreed to join and well these are a little out of the ordinary. However I do enjoy video games, it's not like I do anything else in my spare time.")
	await o.say("YOU","Besides, it's not like the other clubs are that appealing.")
	await k.say("KING","\"You know it's bad manners to be hounding people like that.\"")
	await k.say("KING","\"You'll only end up scaring them away.\"")
	await k.say("KING","\"At this rate you'll only end up running the club into the ground.\"")
	await o.say("Sentry","\"I'm sorry club leader! I wont mess up again!\"")
	# Jeg er for træt, så jeg arbejder videre en anden dag
	await q.say("Quickshot", "\"\"")
	await o.say("YOU","\"\"")
	await o.say("YOU","")
	await k.say("KING","\"\"")
	await o.say("YOU","\"\"")
	await o.say("Sentry","\"\"")
	await h.say("Harbinger","\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("YOU","")
	await q.say("Quickshot", "\"\"")
	await q.say("Quickshot", "\"\"")
	await h.say("Harbinger","\"\"")
	await o.say("YOU","")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await k.say("KING","\"\"")
	await h.say("Harbinger","\"\"")
	await q.say("Quickshot", "\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await h.say("Harbinger","\"\"")
	await r.say("Ravager","\"\"")
	await k.say("KING","\"\"")
	await q.say("Quickshot", "\"\"")
	await k.say("KING","\"\"")
	await o.say("YOU","")
	await o.say("YOU","")
	await o.say("Sentry","\"\"")
	await r.say("Ravager","\"\"")
	await o.say("Sentry","\"\"")
	await q.say("Quickshot", "\"\"")
	await o.say("YOU","")
	await o.say("YOU","")

func wait(seconds:float) -> Signal:#Laver en timer til at holde øje med tiden (bruges andre til dialog box)
	return get_tree().create_timer(seconds).timeout

func _on_settings_button_down() -> void:#Åbner settings når settings knap trykkes
	VarOverlay.showMeSettings()#Kalder det fra VarOverlay script, som er globalt

func _on_save_button_down() -> void:#Samme som ovenfor
	VarOverlay.showMeSaves()

func _input(event)->void:#Åbner eller lukker escape menu når escape bliver trykket
	if event.is_action_pressed("escPressed"):
		if GlobalVar.escOpen==false:#Åbner hvis den ikke er åben
			print(GlobalVar.escOpen)
			print("opening escMenu")
			VarOverlay.showMeEsc()#Kører det igennem det globale script
			GlobalVar.escOpen=true
		elif GlobalVar.escOpen and GlobalVar.openRelease:#Hvis den er åben, så lukker den
				VarOverlay.overlayEsc.queue_free()
				GlobalVar.escOpen=false


func _on_menu_pressed() -> void:
	VarOverlay.showMeEsc()
	GlobalVar.escOpen=true
