class_name SetDressing extends Control

#loader karakterene som scener
const CHARA1 = preload("res://character_example.tscn")
const CHARA2 = preload("res://character_example2.tscn")
const CHARA3 = preload("res://character_example_3.tscn")
const CHARA4 = preload("res://character_example_3.tscn")
const CHARA5 = preload("res://character_example_3.tscn")

func _ready() -> void:
	#instantiater karakterene
	var o:VNCharacter=CHARA1.instantiate()
	var r:VNCharacter=CHARA2.instantiate()
	var q:VNCharacter=CHARA3.instantiate()
	var h:VNCharacter=CHARA4.instantiate()
	var k:VNCharacter=CHARA5.instantiate()
	#tilføjer dem til scenen
	add_child(o)
	add_child(r)
	add_child(q)
	add_child(h)
	add_child(k)
	#kommandoer som kan udføres:
	#_.snap(%position)
	#_.move(%position,tid brugt på bevægelse)
	#_.say("navn", "Hvad der skal siges") (brug \n til at gå en linje ned og tilføj 2 mellemrum)
	#_.flip_(h/v)=(true/false)
	#_.attr("navn på alternativ udseende på karakter")
	#await venter på den sidste kommando er færdig til at udføre den næste
	o.snap(%far_left)
	r.snap(%far_left)
	q.snap(%far_left)
	h.snap(%far_left)
	k.snap(%far_left)
	%background.texture=load("res://backgrounds/Classroom.png")
	var transition1=create_tween()
	transition1.tween_property(%background, "modulate:a", 0, 0)
	transition1.tween_property(%background, "modulate:a", 1, 2)
	await o.move(%far_left,2.5)
	await o.say("Self","It’s only been a few weeks since I’ve started high school.\n  So far high school life has been as dull as I expected. \n  It’s nothing like how it is in manga.")
	await o.say("Self","I still have to join a club soon,\n  I’ve been waiting it out for a good while now.\n  It’s practically been pushed to the back of my mind.")
	await o.say("Self","I could continue to wait till the festival, \n  all the different clubs should be at their \n  best marketing-wise then.")
	await o.say("Self","But, it would be embarrassing to be walking around\n  as one of those clubless. Especially if everyone else \n  has already found a club.")
	await o.say("Self","Yeah, that’s definitely not happening.")
	await o.say("Self","But what kind of club should I even join? \n  Perhaps something that doesn’t require much. \n  Like some kind of manga or anime club.")
	await o.say("Self","If we even have clubs like that…")
	await o.say("Self","Guess I really have to go around looking after school.")
	await o.say("Self","After class finishes, I continue to sit at\n  my desk and wait a bit longer. \n  Building up the courage to go club hunting")
	await o.say("Self","I would rather not have my classmates think\n  I’m some loser. After all, I only go home and do nothing\n  but play video games.")
	await o.say("Self","Not long after dismissal, everyone funneled out the\n  classroom, heading to their own after school activities.")
	await o.say("Self","I wait for the coast to be clear before I make my move.")
	await o.say("Self","I gather my belongings and leave like everyone else.\n  Except this time, I’m not going home.")
	var transition2=create_tween()
	transition2.tween_property(%background, "modulate:a", 0, 1.5)
	await o.move(%far_left,2)
	%background.texture=load("res://backgrounds/HallwayLeftToRight.png")
	var transition3=create_tween()
	transition3.tween_property(%background, "modulate:a", 0, 0)
	transition3.tween_property(%background, "modulate:a", 1, 1.5)
	await o.move(%far_left,2)
	await o.say("Self","I walk down the hallway. I can’t help but feel out of place,\n  even though I’ve been here multiple times every day. \n  It feels like I took a wrong turn on a familiar road.")
	await o.say("Self","I’ve already passed a few clubs by now, \n  but none of them stood out to me.")
	await o.say("Self","Luckily no one's seen me out here yet. \n  The worst thing that could happen right now is-")
	await o.move(%leftishUpleftUp,0.5)
	await o.move(%leftish,0.5)
	await o.say("Sentry","\"CRAP I’M GONNA BE LATE!!!\"")
	await o.say("Self","Then, like clockwork I run into an old friend, \n  the one thing I was trying to avoid.")
	await o.say("Self","He’s running through the halls like a complete lunatic, \n  almost running straight into me.")
	await o.move(%leftishDownLeft,0.5)
	await o.say("Self","He barely misses me, I’d have hoped he kept going. \n  But he stops dead in his tracks and turns to me, \n  definitely recognizing me.")
	await o.move(%centerUp, 0.75)
	o.flip_h=true
	await o.say("Sentry","\"YOU!\"")
	await o.say("Sentry","\"Uh It's you!\"")
	await o.say("Sentry","\"From last year.\"")
	await o.say("Sentry","\"No not last year-\"")
	await o.say("Self","Last year I would still have been in middle school. It’s been a while since then, we didn’t know each other exactly.")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await o.say("Self","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")#
	await o.say("Sentry","\"\"")
	await o.say("Self","")
	await o.say("Self","")#
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")#
	await o.say("Self","")
	await o.say("Self","")#
	await o.say("Sentry","\"\"")
	await o.say("Self","")#
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")#
	await o.say("Sentry","\"\"")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")#
	await o.say("Self","")
	await o.say("Self","")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await o.say("Self","")
	await r.say("Rav","\"\"")
	await q.say("Q", "\"\"")
	await r.say("Rav","\"\"")
	await h.say("Harbinger","\"\"")
	await h.say("Harbinger","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await h.say("Harbinger","\"\"")
	await o.say("Self","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")
	await q.say("Q", "\"\"")
	await q.say("Q", "\"\"")
	await h.say("Harbinger","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await q.say("Q", "\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await k.say("KING","\"\"")
	await o.say("Self","")
	await q.say("Q", "\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")
	await k.say("KING","\"\"")
	await o.say("Sentry","\"\"")
	await k.say("KING","\"\"")
	await o.say("Self","\"\"")
	await o.say("Self","")
	await r.say("Rav","\"\"")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Self","")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Sentry","\"\"")
	await q.say("Q", "\"\"")
	await o.say("Self","")
	await q.say("Q", "\"\"")
	await q.say("Q", "\"\"")
	await k.say("KING","\"\"")
	await h.say("Harbinger","\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Self","")
	await q.say("Q", "\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("Sentry","\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Self","")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("Self","")
	await o.say("Self","")
	await o.say("Self","")
	await o.say("Self","")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("Sentry","\"\"")
	await q.say("Q", "\"\"")
	await o.say("Self","\"\"")
	await o.say("Self","")
	await k.say("KING","\"\"")
	await o.say("Self","\"\"")
	await o.say("Sentry","\"\"")
	await h.say("Harbinger","\"\"")
	await k.say("KING","\"\"")
	await k.say("KING","\"\"")
	await o.say("Self","")
	await q.say("Q", "\"\"")
	await q.say("Q", "\"\"")
	await h.say("Harbinger","\"\"")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await k.say("KING","\"\"")
	await h.say("Harbinger","\"\"")
	await q.say("Q", "\"\"")
	await o.say("Sentry","\"\"")
	await o.say("Sentry","\"\"")
	await h.say("Harbinger","\"\"")
	await r.say("Rav","\"\"")
	await k.say("KING","\"\"")
	await q.say("Q", "\"\"")
	await k.say("KING","\"\"")
	await o.say("Self","")
	await o.say("Self","")
	await o.say("Sentry","\"\"")
	await r.say("Rav","\"\"")
	await o.say("Sentry","\"\"")
	await q.say("Q", "\"\"")
	await o.say("Self","")
	await o.say("Self","")

func wait(seconds:float) -> Signal:#Laver en timer til at holde øje med tiden (bruges andre til dialog box)
	return get_tree().create_timer(seconds).timeout

func _on_settings_button_down() -> void:#Åbner settings når settings knap trykkes
	VarOverlay.showMeSettings()#Kalder det fra VarOverlay script, som er globalt

func _on_save_button_down() -> void:#Samme som ovenfor
	VarOverlay.showMeSaves()

func _on_skip_button_down() -> void:#Ikke færdigt
	pass # Replace with function body.

func _input(event)->void:#Åbner eller lukker escape menu når escape bliver trykket
	if event.is_action_pressed("escPressed"):
		if GlobalVar.escOpen==false:#Åbner hvis den ikke er åben
			print(GlobalVar.escOpen)
			print("opening escMenu")
			VarOverlay.showMeEsc()#Kører det igennem det globale script
			GlobalVar.escOpen=true
		elif GlobalVar.escOpen and GlobalVar.openRelease:#Hvis den er åben, så lukker den
				VarOverlay.overlayEsc.queue_free()
				GlobalVar.escOpen=false
