extends SetDressing
#loader karakterene som scener

func _ready() -> void:
	#instantiater karakterene
	var o:VNCharacter=CHARA1.instantiate()
	var r:VNCharacter=CHARA2.instantiate()
	var q:VNCharacter=CHARA3.instantiate()
	var h:VNCharacter=CHARA4.instantiate()
	var k:VNCharacter=CHARA5.instantiate()
	#tilføjer dem til scenen
	add_child(o)
	add_child(r)
	add_child(q)
	add_child(h)
	add_child(k)
	#kommandoer som kan udføres:
	#_.snap(%position)
	#_.move(%position,tid brugt på bevægelse)
	#_.say("navn", "Hvad der skal siges") (brug \n til at gå en linje ned og tilføj 2 mellemrum)
	#_.flip_(h/v)=(true/false)
	#_.attr("navn på alternativ udseende på karakter")
	#await venter på den sidste kommando er færdig til at udføre den næste
	o.snap(%OOSL)
	r.snap(%OOSL)
	q.snap(%OOSL)
	h.snap(%OOSL)
	k.snap(%OOSL)
	%background.texture=load("res://backgrounds/Classroom.png")
	var transition1=create_tween()
	transition1.tween_property(%background, "modulate:a", 0, 0)
	transition1.tween_property(%background, "modulate:a", 1, 2)
	await o.move(%OOSL,2.5)
	o.snap(%"09")
	r.snap(%"OOSL")
	q.snap(%"16")
	k.snap(%"10")
	h.snap(%"15")
	await h.move(%"19",1)
	h.flip_h=true
	await h.say("Harbinger", "\"Hm.\"")
	await o.say("YOU", "\"What's the matter.\"")
	await h.say("Harbinger", "\"It's nothing, I merely recognize the title.\"")
	await h.move(%"15",1)
	await k.say("KING", "\"Alright let me collect the games, \n  I'll store them in the supply closet for the time being.\"")
	k.move(%"17",0.5)
	k.move(%"13",1.25)
	k.move(%"14",0.5)
	k.move(%"11",0.75)
	await o.say("YOU", "KING goes around collecting every game we brought, \n  and goes to the closet to store them. \n  While he does that Q goes over everything we need to get done before the day ends.")
	await q.say("Quickshot", "\"We will need to set up the extra computers, we have been given. \n  Those should be down in the gym storage room.\"")
	await q.say("Quickshot", "\"Sentry, could you go get those. \n  If you meet Ravager on the way tell him to help you out.\"")
	await o.say("Sentry", "\"Aye aye captain!\"")
	await q.say("Quickshot", "\"Alright, then Harbinger and I will handle all the flyers and decorations, \n  just like last year.\"")
	await q.say("Quickshot", "\"Which just leaves the new guy and-\"")
	await k.say("KING", "\"Actually, I could really use your help this time around Q.\"")
	await k.say("KING", "\"I'm still pretty unsure about \n  all this club signage student counsel mumbo jumbo.\"")
	await q.say("Quickshot", "\"Oh uh, sure I can help out with that.\"")
	await q.say("Quickshot", "\"Then-\"")
	await h.say("Harbinger", "\"But you promised.\"")
	await q.say("Quickshot", "\"I'll have to help out KING with this.\"")
	await q.say("Quickshot", "\"We'll need to get this done today.\"")
	await q.say("Quickshot", "\"You've done this before, and you'll have help, \n  you'll just have to show the new guy where the things will need to go.\"")
	await q.say("Quickshot", "\"It'll be fine.\"")
	await h.say("Harbinger", "\"Tch!\"")
	await h.say("Harbinger", "\"I know...\"")
	q.move(%"14",1.5)
	await q.say("Quickshot", "\"Alright, if you meet Ravager on the \n  way tell him to come back here.\"")
	await q.move(%"07",0.25)
	await wait(1)
	q.snap(%"OOSL")
	await o.say("YOU", "Before leaving Q hands Harb a USB drive \n  with what I assume has all that we need printed on it.")
	await o.say("YOU", "Now we only need to get it printed at the school library.")
	await o.say("YOU", "Harb turns to leave without saying a word, \n  almost leaving me behind.")
	await o.say("YOU", "\"Hey wait up!\"")
	await h.say("Harbinger", "\"If you can't keep up don't bother.\"")
	await o.say("YOU", "\"What?\"")
	await h.say("Harbinger", "\"...\"")
	h.move(%"07")
	await o.say("YOU", "Harb begins walking as if they didn't even hear me.")
	await o.say("YOU", "\"Hey! Wait a minute!\"")
	await o.say("YOU", "\"You can't just-\"")
	h.flip_h=false
	h.move(%"13",0.1)
	await h.say("Harbinger", "\"L!ST#N\"")
	await h.say("Harbinger", "\"IF YOU D0N'T STOP GETTING !N THE W5Y I SW3AR\"")
	await h.say("Harbinger", "\"...\"")
	await h.say("Harbinger", "\"Let's just get this over with.\"")
	await h.say("Harbinger", "\"And...uh sorry.\"")
	await h.say("Harbinger", "\"It's just...\"")
	await h.say("Harbinger", "\"never mind.\"")
	await o.say("YOU", "\"Are you...okay?\"")
	await h.say("Harbinger", "\"Tch\"")
	await h.say("Harbinger", "\"I must still be a little angry from earlier.\"")
	await o.say("YOU", "\"What happened?\"")
	await h.say("Harbinger", "\"Ugh...Ravager.\"")
	await h.say("Harbinger", "\"He...\"")
	await h.say("Harbinger", "\"Let's just get this done. We still have to get to the library\"")
	await o.say("YOU", "\"We can walk and talk if you want.\"")
	await h.say("Harbinger", "\"Hm sure. As long as we don't take forever.\"")
	await o.say("YOU", "\"So what’s with you and Ravager?\"")
	await h.say("Harbinger", "\"We just got into a fight is all.\"")
	await o.say("YOU", "\"Why? Aren't the two of you friends?\"")
	await h.say("Harbinger", "\"Tch!\"")
	await h.say("Harbinger", "\"As if I could be friends with someone like that!\"")
	await h.say("Harbinger", "\"Friends don't make friends turn on each other.\"")
	await o.say("YOU", "\"Huh? What do you mean?\"")
	await h.say("Harbinger", "\"Hah that fiend really thought I would believe his lies.\"")
	await h.say("Harbinger", "\"You've met Q, you know he's a great guy.\"")
	await o.say("YOU", "\"He said something about Q?\"")
	await h.say("Harbinger", "\"Well not just Q...\"")
	await h.say("Harbinger", "\"But there's no way!\"")
	await h.say("Harbinger", "\"Q wouldn't...\"")
	await h.say("Harbinger", "\"He wouldn't.\"")
	await h.say("Harbinger", "\"K!NG...\"")
	await o.say("YOU", "\"Uhm Harbinger?\"")
	await h.say("Harbinger", "\"The library, let's just print quick.\"")
	await h.say("Harbinger", "\"I'll go print, wait here.\"")
	await h.say("Harbinger", "\"Afterwards let's split up it would be quicker.\"")
	await o.say("YOU", "\"Of course, just let me know if you need any help.\"")
	await o.say("YOU", "Seems like there's a lot going on behind the scenes. \n  Especially between Harb and Rav, I never expected \n  them to not get along like this...")
	await o.say("YOU", "Harbinger sure seems to be on edge. \n  They've been getting quieter, like they have a lot on their mind.")
	await o.say("YOU", "Harbinger come over to me and hands me \n  a small stack of flyers and a box of thumbtacks.")
	await h.say("Harbinger", "\"Go\"")
	await o.say("YOU", "\"Uh what of-\"")
	await h.say("Harbinger", "\"I'll handle the rest.\"")
	await h.say("Harbinger", "\"Just go.\"")
	await o.say("YOU", "\"Okay...\"")
	await o.say("YOU", "I spend pretty much the rest of the day \n  going around half the school setting up posters.")
	await o.say("YOU", "Strangely though there doesn't seem to be anyone else. \n  The place is completely deserted.")
	await o.say("YOU", "I haven't met a single person not even Harbinger.")
	

func wait(seconds:float) -> Signal:#Laver en timer til at holde øje med tiden (bruges andre til dialog box)
	return get_tree().create_timer(seconds).timeout

func _on_settings_button_down() -> void:#Åbner settings når settings knap trykkes
	VarOverlay.showMeSettings()#Kalder det fra VarOverlay script, som er globalt
	%UiSimpleConfirm.play()

func _on_save_button_down() -> void:#Samme som ovenfor
	VarOverlay.showMeSaves()
	%UiSimpleConfirm.play()

func _input(event)->void:#Åbner eller lukker escape menu når escape bliver trykket
	if event.is_action_pressed("escPressed"):
		if GlobalVar.escOpen==false:#Åbner hvis den ikke er åben
			%UiSimpleSelect.play()
			print(GlobalVar.escOpen)
			print("opening escMenu")
			VarOverlay.showMeEsc()#Kører det igennem det globale script
			GlobalVar.escOpen=true
		elif GlobalVar.escOpen and GlobalVar.openRelease:#Hvis den er åben, så lukker den
			%UiSimpleCancel.play()
			VarOverlay.overlayEsc.queue_free()
			GlobalVar.escOpen=false


func _on_menu_pressed() -> void:
	%UiSimpleConfirm.play()
	VarOverlay.showMeEsc()
	GlobalVar.escOpen=true
